### ISSUE TITLE
Working directory not correctly set

### ISSUE THREAD

**Issue by jasonkoon** [ranorex/Jenkins-Ranorex-Plugin#6] opened 2018-03-15 15:42 UTC
# Feature/Bug description:
Working directory is not being set correctly in 0.1.2 or 0.1.3.

Jenkins workspace looks like this
workspace\Jenkins_project\project\testsolution\file.rxsln   

the working directory should be
workspace\Jenkins_project\project\testsolution\testProject\bin\debug\

the working directory is
workspace\Jenkins_project\project\bin\debug\

# Steps to reproduce:
1.Create matching git repo folder structure
2.Add Ranorex test suite
3.Create a Ranorex Jenkins job to execute the test suite.

# Observed behavior

FATAL: execution failed
java.io.IOException: Process working directory 'C:\jenkins_root\workspace\Jenkins_project\bin\Debug' doesn't exist!

**Comment by ahoisl** [comment] 2018-03-15 15:49
Could this be a duplicate of #4 ?

**Comment by jasonkoon** [comment] 2018-03-15 16:19
I think that the fix for #4 broke my situation?  
My situation didn't rely on paths relative to the working directory, so as long as it existed the test would work.  Now though the working directory is being set to an invalid directory so the test fails.  I tried 0.1.2 and 0.1.3.

**Comment by Mstoegerer** [comment] 2018-03-15 19:36
Hey jasonkoon,
we are working on it. Please excuse the inconveniences.

**Comment by sknopper** [comment] 2018-03-16 07:26
Hello jasonkoon,

thank you for reaching out to us. Unfortunately we are not able to reproduce your issue. Therefore I assume that there might be a configuration error because of the working directory changes. May I ask you to reach out to us at evaluation@ranorex.com so that we can check your configuration together?

**Comment by Mstoegerer** [comment] 2018-03-19 12:18
Fixed with 0.1.4

**Closed by Mstoegerer** 2018-03-19 12:18 UTC
Labels: bug

**Comment by jasonkoon** [comment] 2018-03-19 13:53
This fixed it.  Turns out our paths had backslashes instead of forward slashes.  Thanks!
